name: a

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
             pwd
             npm -v
             echo $GITHUB_WORKSPACE
      - run: mkdir a && cd a && pwd
      - run: pwd
